### ISSUE TITLE
Error converting releases when Helm v2 secret storage backend set using "args" field of the container spec

### ISSUE THREAD

**Issue by hickert33** [helm/helm-2to3#112]
KUBE:
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

HELM
helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

Tiller is in the `kube-system` namespace using secrets to hold v2 configuration.  Tiller was configured for secret storage backend as follows: `tiller --override 'spec.template.spec.containers[0].args'='{/tiller,--storage=secret}'`

$ helm3 2to3 convert microservice --dry-run
2020/01/23 12:06:07 NOTE: This is in dry-run mode, the following actions will not be executed.
2020/01/23 12:06:07 Run without --dry-run to take the actions described below:
2020/01/23 12:06:07
2020/01/23 12:06:07 Release "microservice" will be converted from Helm v2 to Helm v3.
2020/01/23 12:06:19 [Helm 3] Release "microservice" will be created.
Error: microservice has no deployed releases
Error: plugin "2to3" exited with error

Any ideas?

_Originally posted by @hickert33 in https://github.com/helm/helm-2to3/issues/97#issuecomment-577805600_

**Comment by hickeyma** [comment]
@hickert33 What is the output of the command: `kubectl get secret -n kube-system -l "OWNER=TILLER"`?

**Comment by hickert33** [comment]
@hickeyma   

 helm 2to3 convert --dry-run metrics-server
2020/01/27 09:19:26 NOTE: This is in dry-run mode, the following actions will not be executed.
2020/01/27 09:19:26 Run without --dry-run to take the actions described below:
2020/01/27 09:19:26
2020/01/27 09:19:26 Release "metrics-server" will be converted from Helm v2 to Helm v3.
2020/01/27 09:19:26 [Helm 3] Release "metrics-server" will be created.
Error: metrics-server has no deployed releases
Error: plugin "2to3" exited with error

kubectl get secret -n kube-system -l "OWNER=TILLER"
NAME                               TYPE     DATA   AGE
metrics-server.v1                  Opaque   1      20d

Other services I attempt to convert are in my "default" namespace but getting the same error upon convert. And their secrets are also in kube-system.  

One note, I use TLS to talk to tiller with helm2. Tiller is in kube-system.

**Comment by hickeyma** [comment]
ok, can you show helm 2 `list` command with command and output shown?

**Comment by hickert33** [comment]
$ helm list --tls
NAME                            REVISION        UPDATED                         STATUS          CHART                                                   APP VERSION                             NAMESPACE
metrics-server                  1               Mon Jan  6 11:26:41 2020        DEPLOYED        metrics-server-2.8.8                                    0.3.5                                   kube-system

**Comment by justinturpin** [comment]
So I am having this issue as well and am actively trying to debug it - it looks like the storage thinks it's "configmaps" when it should be "secrets".  I have filed this issue with the helm-plugin-utils repo here: https://github.com/maorfr/helm-plugin-utils . It seems like an easy enough fix and I tested it locally and it seems to work.

**Comment by hickert33** [comment]
I have upgraded without converting so this is a non-issue for me now, but can leave open until @justinturpin gets his fix merged...

**Comment by sppwf** [comment]
Hi Guys,

When do you think this will be implemented?
Even I use "--release-storage secrets" i still get same error 

Thanks
Ser

**Comment by suciuandrei94** [comment]
Hello guys, I've altered an existing GO library to migrate secrets to configmap so this problem with migration doesn't happen anymore.

[here](https://github.com/suciuandrei94/tiller-releases-converter)

**Comment by dragonsmith** [comment]
I've merged the PR.

Here are the binaries:
1. (Old libs v1.10) https://github.com/dragonsmith/tiller-releases-converter/releases/tag/0.1.3
2. (New libs v1.17) https://github.com/dragonsmith/tiller-releases-converter/releases/tag/0.1.4

**Comment by hickeyma** [comment]
@hickert33 @justinturpin Thanks for finding and working on this issue. Sorry for the delay in responding.

I have been trying to reproduce this issue but cannot seem to make it happen. Here is my some idea of my set-up:

```console
$ helm2 init --tiller-tls --tiller-tls-cert ./tiller.cert.pem --tiller-tls-key ./tiller.key.pem --tiller-tls-verify --tls-ca-cert ca.cert.pem --service-account tiller --override 'spec.template.spec.containers[0].command'='{/tiller,--storage=secret}'
Creating /root/.helm 
Creating /root/.helm/repository 
Creating /root/.helm/repository/cache 
Creating /root/.helm/repository/local 
[...]

$ helm2 ls --tls
NAME       	REVISION	UPDATED                 	STATUS  	CHART         	APP VERSION	NAMESPACE
mychart-v2 	1       	Mon Feb 17 15:52:52 2020	DEPLOYED	mychart-0.1.0 	1.0        	default  
newchart-v2	1       	Mon Feb 17 15:55:15 2020	DEPLOYED	newchart-0.1.0	1.0        	default  

$ kubectl get secret -n kube-system -l "OWNER=TILLER"
NAME             TYPE     DATA   AGE
mychart-v2.v1    Opaque   1      8m25s
newchart-v2.v1   Opaque   1      6m2s

$ helm 2to3 convert newchart-v2
2020/02/17 15:55:58 Release "newchart-v2" will be converted from Helm v2 to Helm v3.
2020/02/17 15:55:58 [Helm 3] Release "newchart-v2" will be created.
2020/02/17 15:55:58 [Helm 3] ReleaseVersion "newchart-v2.v1" will be created.
2020/02/17 15:55:58 [Helm 3] ReleaseVersion "newchart-v2.v1" created.
2020/02/17 15:55:58 [Helm 3] Release "newchart-v2" created.
2020/02/17 15:55:58 Release "newchart-v2" was converted successfully from Helm v2 to Helm v3.
[....]

$ helm3 ls
NAME         	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART             	APP VERSION
mychart-v2   	default  	1       	2020-02-17 15:21:46.94726095 +0000 UTC 	deployed	mychart-0.1.0     	1.0        
newchart-v2  	default  	1       	2020-02-17 15:55:15.184427935 +0000 UTC	deployed	newchart-0.1.0    	1.0 

```

Can you provide more details on where the issue is?

**Comment by justinturpin** [comment]
In some installations of Helm, the Tiller command that sets the storage to use secrets is in the "args" field of the container spec, not the command field. This caused the helm-plugin-utils library to think that the Tiller storage was configmaps, causing helm2to3 to look in configmaps and then fail when none could be found.

This PR https://github.com/maorfr/helm-plugin-utils/pull/11 fixes it and got merged in a couple days ago, so theoretically everything should be good to go, but I haven't done a full end to end test yet.

**Comment by hickeyma** [comment]
This is interesting @justinturpin. I was unaware of people setting it using the `args` field.
I saw the fix in the utils project, thanks for that.

To finish the fix on this issue, do you mind pushing a PR to:
- Update https://github.com/helm/helm-2to3/blob/master/go.mod#L8 to use the latest release
- "0.3.0" --> "0.3.1" in https://github.com/helm/helm-2to3/blob/master/plugin.yaml#L2

**Comment by hickeyma** [comment]
@hickert33 @justinturpin I have updated the titler and description to better describe the problem. Thanks for finding and working on this issue.

**Comment by hickeyma** [comment]
> Even I use "--release-storage secrets" i still get same error

@sppwf This flag is only to be used when Tiller is not running in the cluster. When not running in the cluster, it is not possible to know which backend Tiller is using.

**Comment by gau1991** [comment]
Hi @hickeyma ,

We are also facing same issue into our environment, so I have created PR: #124 . Can you please review it and merge it?

**Comment by hickeyma** [comment]
Thanks @justinturpin and @gau1991 for the work on adding the fix for this. It is great to find edge cases like this.
